# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TopSappMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  rn_sqlite_path = '../node_modules/react-native-sqlite-storage'
  rn_path = '../node_modules/react-native'
  permissions_path = '../node_modules/react-native-permissions/ios'


  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Pods for TopSappMobile

  pod 'react-native-sqlite-storage', path: rn_sqlite_path

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'


  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-photo-view-ex', :path => '../node_modules/react-native-photo-view-ex'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'react-native-maps', :path => '../node_modules/react-native-libs/react-native-maps-osmdroid'

  #pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-signature-capture', :path => '../node_modules/react-native-signature-capture'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders.podspec"
  pod 'Permission-Siri', :path => "#{permissions_path}/Siri.podspec"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit.podspec"

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'RNImageMarker', :path => '../node_modules/react-native-image-marker'

  pod 'toolbar-android', :path => '../node_modules/@react-native-community/toolbar-android'

  pod 'RNReactNativeDocViewer', :path => '../node_modules/react-native-doc-viewer'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|


    if target.name == "yoga"
      target.remove_from_project
    end



    if target.name == "RNFirebase"
      target.remove_from_project
    end

    if target.name == 'react-native-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end

    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")

  end
end



def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
